### ISSUE TITLE
no filter to dispatch events to different specified out sink  

### ISSUE THREAD

**Issue by chenqiangzhishen** [AliyunContainerService/kube-eventer#135]
As described in the title, we want the function to dispatch events to different out sink,
for example as bellows, I coped it from https://github.com/opsgenie/kubernetes-event-exporter
```
route:
  # Main route
  routes:
    # This route allows dumping all events because it has no fields to match and no drop rules.
    - match:
      - receiver: dump
    # This starts another route, drops all the events in *test* namespaces and Normal events
    # for capturing critical events
    - drop:
      - namespace: "*test*"
      - type: "Normal"
      match:
      - receiver: "critical-events-queue"
    # This a final route for user messages
    - match:
        kind: "Pod|Deployment|ReplicaSet"
        labels:
          version: "dev"
        receiver: "slack"
receivers:
# See below for configuring the receivers
```

**Comment by ringtail** [comment]
sure! you can use multi sinks as args.

**Comment by chenqiangzhishen** [comment]
@ringtail ，I mean using the same sink (eg. Kafka sink), but  would use some filters (eg. regexp) to select different k8s-events to different topics. 

## the basic usage is to filter namepaced events to different topics. such as
```
 defaut namespace -> default topic
 kube-system namespace -> kube-system topic
```
## the advanced usage is to filter specified type event to different topic, such as
```
outofmemory event -> outofevent topic 
backoff event -> backoff topic
```

**Comment by chijiajian** [comment]
> sure! you can use multi sinks as args.

I think @chenqiangzhishen need option to filter out some events, according to their properties by ConfigMap. 
For example
```
route:
   - match:
     - namespace: "*ns_name*"
     - type: "Warning"
     - outsink: "topic1"  #or another out sink media
```
according to their properties to drop messages also.
