### ISSUE TITLE
我想同时发送到elasticsearch和webhook，请问如何配置sink？

### ISSUE THREAD

**Issue by 4220182** [AliyunContainerService/kube-eventer#162]
```
 command:
            - "/kube-eventer"
            - "--source=kubernetes:https://kubernetes.default"
            ## .e.g,dingtalk sink demo
            - --sink=elasticsearch:https://es.mytest.com/
            - --sink=webhook:https://webhook.mytest.com?key=AIzaSy&token=_OJqU
```
 
提示 webhook(MISSING)：

kubectl logs kube-eventer-xxxxx-xxx -n kube-system
I1221 13:36:15.553947       1 eventer.go:67] /kube-eventer --source=kubernetes:https://kubernetes.default --sink=elasticsearch:https://https://es.mytest.com/ --sink=webhook:https://webhook.mytest.com?key=AIzaSy&token=_OJqU(MISSING)

**Comment by ringtail** [comment]
没有复现出你的问题，麻烦贴下你的完整Yaml

**Comment by 4220182** [comment]
webhook 我使用google chat 。

deployment-events.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: kube-eventer
  name: kube-eventer
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-eventer
  template:
    metadata:
      labels:
        app: kube-eventer
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccount: kube-eventer
      nodeSelector:
         tools: base
      containers:
        - image: registry.aliyuncs.com/acs/kube-eventer-amd64:v1.2.0-484d9cd-aliyun
          imagePullPolicy: IfNotPresent
          name: kube-eventer
          command:
            - "/kube-eventer"
            - "--source=kubernetes:https://kubernetes.default"
            ## .e.g,dingtalk sink demo
            - --sink=elasticsearch:https://xxxxxxxxxxxxx.cn-north-1.es.amazonaws.com.cn:443?sniff=false&ver=7&index=myevents&esUserName=myuser&esUserSecret=password
            - --sink=webhook:https://chat.googleapis.com/v1/spaces/xxxxxx/messages?key=xxxxxxxxxx-xxxxxxxxxx&token=xxxxxxxxxx-xxxxxxx
          env:
          # If TZ is assigned, set the TZ value as the time zone
          - name: TZ
            value: "Asia/Shanghai"
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: zoneinfo
              mountPath: /usr/share/zoneinfo
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 250Mi
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: zoneinfo
          hostPath:
            path: /usr/share/zoneinfo

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-eventer
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-eventer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-eventer
subjects:
  - kind: ServiceAccount
    name: kube-eventer
    namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-eventer
  namespace: kube-system
```
