### ISSUE TITLE
-log_dir和-log_file不生效

### ISSUE THREAD

**Issue by liuxue-2000** [AliyunContainerService/kube-eventer#300]
配置如下，在镜像中已授权，并使用root启动
![image](https://github.com/user-attachments/assets/26093c9c-d2d5-4d63-860f-13d4e8169a47)
![image](https://github.com/user-attachments/assets/e09643a7-788f-40e2-8cc8-1b72c43dd183)

是还需要其他权限？还是哪里配置不对呢

**Comment by yusheng-guo** [comment]
Hi @liuxue-2000 , I have carefully reviewed your question.

First, in klog v1.0.0, the options `--log_dir` and `--log_file` cannot be used simultaneously. You can find more details [here](https://github.com/kubernetes/klog/blob/2ca9ad30301bf30a8a6e0fa2110db6b8df699a91/klog.go#L480-L486).

Second, if you built the image using the project's [Dockerfile](deploy/Dockerfile) or [Dockerfile.multi](deploy/Dockerfile.multi), please note that the image runs the program with non-root permissions. This means it won't work even if you start it with root permissions.

Lastly, to save logs to a specific directory or file, you will need to use Kubernetes Storage. You can find more information [here](https://kubernetes.io/docs/concepts/storage/).

Below is an example of a Deployment configuration that saves logs to a host directory:

```YAML
containers:
  - command:
      - /kube-eventer
      - '--source=<source>'
      - >-
        --sink=<sink>
      - '--log_dir=/var/log/kube-eventer'
    ...
    volumeMounts:
      - mountPath: /var/log/kube-eventer
        name: volume-1732240867108
...
volumes:
  - hostPath:
      path: /tmp
      type: ''
    name: volume-1732240867108
```
