### ISSUE TITLE
配置钉钉webhook url,且也有触发event,但是没有告警到对应机器人

### ISSUE THREAD

**Issue by Eddie-0721** [AliyunContainerService/kube-eventer#304]
#286 跟这个issues一样的情况,希望您尽快帮忙看一下,谢谢

**Comment by yshngg** [comment]
## Webhook Integration (DingTalk Robot Example)

### 1. Obtain Webhook URL and Access Token

To test the DingTalk Robot using `curl`:

```console
$ curl https://oapi.dingtalk.com/robot/send?access_token=<access_token> \
    --request POST \
    --header "Content-Type: application/json" \
    --data '{"msgtype": "text","text": {"content": "Kubernetes Event"}}'
{"errcode":0,"errmsg":"ok"}
```

### 2. Customize HTTP Request Body Template via ConfigMap

> Define the HTTP request body format required by DingTalk Robot using a request template.

Assume **kube-eventer** runs in the **kube-system** namespace.

_`configmap.yaml`_

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook
  namespace: kube-system
data:
  content: '{"msgtype": "text", "text": {"content": "EventMessage: {{ .Message }}"}}'
```

Reference implementation: [webhook.go#L209-L221](https://github.com/AliyunContainerService/kube-eventer/blob/c7c1896954021ccb43c4aee95fe243a0da570161/sinks/webhook/webhook.go#L209-L221)

### 3. Configure RBAC Permissions

Grant **kube-eventer** access to the webhook ConfigMap:

_`role.yaml`_

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kube-system
  name: webhook-configmap-reader
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]
```

_`rolebinding.yaml`_

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webhook-configmap-reader
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: <serviceaccount-usedby-kube-eventer>
    namespace: kube-system
roleRef:
  kind: Role
  name: webhook-configmap-reader
  apiGroup: rbac.authorization.k8s.io
```

### 4. Configure Container Startup Parameters

Set the following parameters:

- HTTP method: POST
- Request header: Content-Type=application/json
- Custom request body:
  - custom_body_configmap=webhook
  - custom_body_configmap_namespace=kube-system

```bash
["/kube-eventer","--source=kubernetes:https://kubernetes.default","--sink=webhook:https://oapi.dingtalk.com/robot/send?access_token=<access_token>&method=POST&level=Normal&header=Content-Type=application/json&custom_body_configmap=webhook&custom_body_configmap_namespace=kube-system"]
```

Hi @KeyOfSpectator , how about adding this documentation to [_`README.md`_](github.com/AliyunContainerService/README.md)
